sources:
  - name: PRACTICE
    database: SNOWFLAKE_PROJECT
    freshness:
          warn_after:
            count: 2
            period: hour
          error_after:
            count: 6
            period: hour
    loaded_at_field: load_date
    tables:
      - name: JSON_DATA
      - name: players_info
        freshness: null
       